version: "3"

services:
  nodeapp:
    build: ./nodeApp
    ports:
      - "3000:3000"

  todoapp:
    build: ./todoApp
    volumes:
      - "./todoApp/src/main/resources/static/todo.json:/todoApp/todo.json"
